export const bioluminescent = {
  id: 'bioluminescent',
  name: 'Bioluminescent',
  description: 'Night sea with electric blue-green glow at every crest.',
  seed: 808,
  waveAmp: 0.7,
  waveSpeed: 0.7,
  windDirection: 150,
  waterColor: 0x04101a,
  deepColor: 0x01040a,
  scatterColor: 0x18ffaa,
  foamColor: 0x88ffd8,
  foamStrength: 0.22,
  sssStrength: 2.6,
  foamThreshold: 0.5,
  foamScale: 1.8,
  roughness: 0.08,
  metalness: 0.18,
  refractionStrength: 0.4,
  reflectionStrength: 0.55,
  refractionDistort: 0.024,
  reflectDistort: 0.014,
  underwaterColor: 0x03101a,
  godRayStrength: 0.14,
  seafloorColor: 0x040a10,
  causticColor: 0x18ffaa,
  causticStrength: 0.6,
  seafloorDepth: -24,
  // Near-dark sky so the crest glow dominates the read. High SSS + bright
  // scatterColor makes every crest edge emit electric blue-green.
  sky: { elevation: 0.6, azimuth: 150, exposure: 0.045, turbidity: 2, cloudCoverage: 0.4 },
  spectrum: {
    lambda: 0.95,
    local: { windSpeed: 4, scale: 0.52, swell: 0.16 },
    swell: { windSpeed: 1.3, scale: 0.46 },
  },
};
